# netlify.toml

# This section tells Netlify how to build your site.
[build]
  # The command to run. We still need this for the API key injection.
  command = "node scripts/inject-env.js"
  
  # The folder that contains all your live website files.
  publish = "public"

# This section is for URL rules.
[[redirects]]
  # When a user goes to "/somalia", serve them the somalia.html file.
  from = "/somalia"
  to = "/somalia.html"
  status = 200 # This is a "rewrite", so the URL in the browser stays clean.