# netlify.toml

[build]
  # Keep your existing build step if you need it
  command  = "node scripts/inject-env.js"
  # Public folder for your site
  publish  = "public"

# Tell Netlify where your serverless functions live
[functions]
  directory = "netlify/functions"

# Route /somalia to the HTML file without changing the URL
[[redirects]]
  from = "/somalia"
  to   = "/somalia.html"
  status = 200